ECommerce/Controllers/FavouriteProductsController.cs
using AutoMapper;
using BusinessLogic.Services;
using BusinessLogic.Utils;
using ECommerce.ViewModel;
using InfraStructure.Entity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace ECommerce.Controllers
{
    public class FavouriteProductsController : Controller
    {
        private readonly IMapper mapper;
        private readonly FavouriteProductRepository favouriteProductRepository;
        public FavouriteProductsController(IMapper _mapper,
            FavouriteProductRepository _favouriteProductRepository)
        {
            mapper = _mapper;
            favouriteProductRepository = _favouriteProductRepository;
        }
        public IActionResult Index()
        {
            var itemsDb = favouriteProductRepository.Find(p => p.IdUser == CurrentUser.Instance.user.Id);
            if (itemsDb.ToList().Count > 0)
            {
                var items = mapper.Map<IEnumerable<FavouriteProductViewModel>>(itemsDb);
                ViewData["userId"] = CurrentUser.Instance.user.Id;
                return View(items);
            }
            return View("EmptyFavourite");
        }

        public IActionResult RemoveAllFromFavouritePage()
        {
            Expression<Func<FavouriteProduct, bool>> predicate =
                p => p.IdUser == CurrentUser.Instance.user.Id;
            favouriteProductRepository.Delete(predicate);
            try
            {
                favouriteProductRepository.SaveChanges();
            }
            catch (Exception e)
            {
                return Json(false);
            }
            return View("EmptyFavourite");
        }
        public JsonResult RemoveFromFavouritePage(int productId)
        {
            var item = new FavouriteProduct();
            item.IdProduct = productId;
            item.IdUser = CurrentUser.Instance.user.Id;
            var data = favouriteProductRepository.Delete(item);
            try
            {
                favouriteProductRepository.SaveChanges();
            }
            catch (Exception e)
            {
                return Json(false);
            }
            return Json(true);
        }
    }
}

ECommerce/Controllers/ProductDetailsController.cs
using AutoMapper;
using BusinessLogic.Services;
using BusinessLogic.Utils;
using ECommerce.ViewModel;
using InfraStructure.Entity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace ECommerce.Controllers
{
    public class ProductDetailsController : Controller
    {
        private readonly IMapper mapper;
        private readonly GenericRepository<Category> categoryRepository;
        private readonly ProductRepository productRepository;
        private readonly CartProductRepository shoppingCartRepository;
        private readonly FavouriteProductRepository favouriteProductRepository;

		public ProductDetailsController(IMapper _mapper, GenericRepository<Category> _categoryRepository,
			ProductRepository _productRepository, CartProductRepository _shoppingCartRepository,
            FavouriteProductRepository _favouriteProductRepository)
		{
			mapper = _mapper;
			categoryRepository = _categoryRepository;
			productRepository = _productRepository;
			shoppingCartRepository = _shoppingCartRepository;
			favouriteProductRepository = _favouriteProductRepository;
		}
		public IActionResult Index(int Id, int CatId)
        {
            if (CatId != null)
            {
                var categoryDb = categoryRepository.GetById(CatId);
                var category = mapper.Map<CategoryShopViewModel>(categoryDb);
                ViewData["Category"] = category;
            }
            var productDb = productRepository.GetById(Id);
            var product = mapper.Map<ProductViewModel>(productDb);

            Expression<Func<Product, bool>> predicate =
               e => e.CategoryId == product.CategoryId && e.Id != product.Id;

            var relatedProductsDb = productRepository.GetRelatedProducts(predicate);
            var relatedProducts = mapper.Map<IEnumerable<ProductViewModel>>(relatedProductsDb);
            ViewData["relatedproducts"] = relatedProducts;
            return View(product);
        }
        [HttpPost]
        public JsonResult AddToShoppingCart(int productId, int quantity)
        {
            var cartItem = new CartItem();
            cartItem.ProductId = productId;
            cartItem.Quantity = quantity;
            cartItem.UserId = CurrentUser.Instance.user.Id;
            var data = shoppingCartRepository.Add(cartItem);
            try
            {
                shoppingCartRepository.SaveChanges();
            }
            catch (Exception e)
            {
                return Json(false);
            }
            return Json(true);
        }

        public JsonResult AddToFavourite(int productId)
        {
            var item = new FavouriteProduct();
            item.IdProduct = productId;
            item.IdUser = CurrentUser.Instance.user.Id;
            var data = favouriteProductRepository.Add(item);
            try
            {
                favouriteProductRepository.SaveChanges();
            }
            catch (Exception e)
            {
                return Json(false);
            }
            return Json(true);
        }
    }
}

ECommerce/Controllers/ShopController.cs
using AutoMapper;
using BusinessLogic.Services;
using BusinessLogic.Utils;
using ECommerce.ViewModel;
using InfraStructure.Entity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ECommerce.Controllers
{
    public class ShopController : Controller
    {
        private readonly IMapper mapper;
        private readonly GenericRepository<Category> categoryRepository;
        private readonly ProductRepository productRepository;
        private readonly CartProductRepository shoppingCartRepository;
        private readonly FavouriteProductRepository favouriteProductRepository;
        public ShopController(IMapper _mapper,
            GenericRepository<Category> _categoryRepository,
            ProductRepository _productRepository,
            CartProductRepository _shoppingCartRepository, FavouriteProductRepository _favouriteProductRepository)
        {
            mapper = _mapper;
            categoryRepository = _categoryRepository;
            productRepository = _productRepository;
            shoppingCartRepository = _shoppingCartRepository;
            favouriteProductRepository = _favouriteProductRepository;
        }
        public IActionResult Index()
        {
            var CategoriesDb = categoryRepository.GetAll();
            var categories = mapper.Map<IEnumerable<CategoryShopViewModel>>(CategoriesDb);
            IEnumerable<Product> productsDb;
            if (TempData["catId"] != null)
            {
                ViewData["catId"] = TempData["catId"];
                productsDb = productRepository.GetByCategory((int)TempData["catId"]);
            }
            else
                productsDb = productRepository.GetAll();

            var products = mapper.Map<IEnumerable<ProductViewModel>>(productsDb);
            ViewData["products"] = products;
            return View(categories);
        }
        public IActionResult GetProductsOfCategory(int id)
        {
            TempData["catId"] = id;
            return RedirectToAction("Index");
        }
        public IActionResult GetProductsOfType(int categoryId, int typeId)
        {
            var productsDb = productRepository.GetByType(categoryId, typeId);
            var products = mapper.Map<IEnumerable<ProductViewModel>>(productsDb);
            ViewData["products"] = products;
            return PartialView("ProductsContent", products);
        }
        [HttpPost]
        public IActionResult GetFilteredProducts(
            IEnumerable<ProductViewModel> products,
            int MaxPrice,
            int MinPrice,
            IEnumerable<string> colors,
            IEnumerable<string> sizes
            )
        {
            var filterdProducts = products.AsQueryable().Where(p => (p.Price <= MaxPrice && p.Price >= MinPrice)).ToList();
            if (colors.Count() > 0)
            {
                filterdProducts = filterdProducts.AsQueryable().Where(p => p.Colors.Any(value => colors.Contains(value.Name))).ToList();
            }
            if (sizes.Count() > 0)
            {
                filterdProducts = filterdProducts.AsQueryable().Where(p => p.Sizes.Any(value => sizes.Contains(value.Name))).ToList();
            }

            ViewData["products"] = filterdProducts;
            return PartialView("ProductsContent", filterdProducts);
        }
        [HttpPost]
        public JsonResult AddToShoppingCart(int productId, int quantity)
        {
            var cartItem = new CartItem();
            cartItem.ProductId = productId;
            cartItem.Quantity = quantity;
            cartItem.UserId = CurrentUser.Instance.user.Id;
            var data = shoppingCartRepository.Add(cartItem);
            try
            {
                shoppingCartRepository.SaveChanges();
            }
            catch (Exception e)
            {
                return Json(false);
            }
            return Json(true);
        }
        [HttpPost]
        public JsonResult AddToFavourite(int productId)
        {
            var item = new FavouriteProduct();
            item.IdProduct = productId;
            item.IdUser = CurrentUser.Instance.user.Id;
            var data = favouriteProductRepository.Add(item);
            try
            {
                favouriteProductRepository.SaveChanges();
            }
            catch (Exception e)
            {
                return Json(false);
            }
            return Json(true);
        }
    }
}

ECommerce/Controllers/ShoppingCartController.cs
using AutoMapper;
using BusinessLogic.Services;
using BusinessLogic.Utils;
using ECommerce.ViewModel;
using InfraStructure.Entity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace ECommerce.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IMapper mapper;
        private readonly CartProductRepository shoppingCartRepository;
        public ShoppingCartController(IMapper _mapper, CartProductRepository _shoppingCartRepository)
        {
            mapper = _mapper;
            shoppingCartRepository = _shoppingCartRepository;
        }
        public IActionResult Index()
        {
            var itemsDb = shoppingCartRepository.Find(p => p.UserId == CurrentUser.Instance.user.Id);
            if (itemsDb.ToList().Count > 0)
            {
                var items = mapper.Map<IEnumerable<CartItemViewModel>>(itemsDb);
                ViewData["userId"] = CurrentUser.Instance.user.Id;
                return View(items);
            }
            return View("EmptyCart");
        }
        public IActionResult RemoveAllFromShoppingCart()
        {
            Expression<Func<CartItem, bool>> predicate =
                p => p.UserId == CurrentUser.Instance.user.Id;
            shoppingCartRepository.Delete(predicate);
            try
            {
                shoppingCartRepository.SaveChanges();
            }
            catch (Exception e)
            {
                return Json(false);
            }
            return View("EmptyCart");
        }
        public JsonResult RemoveFromShoppingCart(int productId)
        {
            var item = new CartItem();
            item.ProductId = productId;
            item.UserId = CurrentUser.Instance.user.Id;
            var data = shoppingCartRepository.Delete(item);
            try
            {
                shoppingCartRepository.SaveChanges();
            }
            catch (Exception e)
            {
                return Json(false);
            }
            return Json(true);
        }
        public JsonResult UpdateShoppingCart(int productId, int productQuantity)
        {
            var item = new CartItem();
            item.ProductId = productId;
            item.UserId = CurrentUser.Instance.user.Id;
            item.Quantity = productQuantity;
            var data = shoppingCartRepository.Update(item);
            try
            {
                shoppingCartRepository.SaveChanges();
            }
            catch (Exception e)
            {
                return Json(false);
            }
            return Json(true);
        }
    }
}

ECommerce/Views/Shared/ProductItem.cshtml
@model ECommerce.ViewModel.ProductViewModel

@{
}
<div class="col-lg-4 col-md-6">
	<div class="product__item">
		<div class="product__item__pic">
			<img src="~/Files/Imgs/Product/@Model.Image" style="width:100%; height:100%" />
			<div class="label new">New</div>
			<ul class="product__hover">
				<li><a href="~/Files/Imgs/Product/@Model.Image" class="image-popup"><span class="arrow_expand"></span></a></li>
				<li><a href="#" onclick="AddToFavourite(@Model.Id)"><span class="icon_heart_alt"></span></a></li>
				<li onclick="AddToCart(@Model.Id)"><a href="#" ><span class="icon_bag_alt"></span></a></li>
			</ul>
		</div>

		<div class="product__item__text">
			<h6><a asp-action="Index" asp-controller="ProductDetails" asp-route-Id="@Model.Id" asp-route-CatId="@ViewData["catId"]">@Model.Name</a></h6>
			<div class="rating">
				<i class="fa fa-star"></i>
				<i class="fa fa-star"></i>
				<i class="fa fa-star"></i>
				<i class="fa fa-star"></i>
				<i class="fa fa-star"></i>
			</div>
			<div class="product__price">$ @Model.Price</div>
		</div>
	</div>
</div>

ECommerce/Views/Shared/ProductsContent.cshtml
@model IEnumerable<ECommerce.ViewModel.ProductViewModel>

<div class="row">
	@foreach (var item in @Model)
	{
		<partial name="ProductItem" model="@item" view-data="ViewData" />
	}

	<div class="col-lg-12 text-center">
		<div class="pagination__option">
			<a href="#">1</a>
			<a href="#">2</a>
			<a href="#">3</a>
			<a href="#"><i class="fa fa-angle-right"></i></a>
		</div>
	</div>
</div>

ECommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
	<meta charset="UTF-8">
	<meta name="description" content="Ashion Template">
	<meta name="keywords" content="Ashion, unica, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Ashion | Template</title>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap"
		  rel="stylesheet">

	<!-- Css Styles -->
	<link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
	<link rel="stylesheet" href="~/css/elegant-icons.css" type="text/css">
	<link rel="stylesheet" href="~/css/jquery-ui.min.css" type="text/css">
	<link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css">
	<link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
	<link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">
	<link href="~/css/sumoselect.css" rel="stylesheet">
	<link rel="stylesheet" href="~/css/style.css" type="text/css">
</head>

<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Offcanvas Menu Begin -->
	<div class="offcanvas-menu-overlay"></div>
	<div class="offcanvas-menu-wrapper">
		<div class="offcanvas__close">+</div>
		<ul class="offcanvas__widget">
			<li><span class="icon_search search-switch"></span></li>
			<li>

				<a asp-action="Index" asp-controller="FavouriteProducts">
					<span class="icon_heart_alt"></span>
					<div class="tip">*</div>
				</a>

			</li>
			<li>

				<a asp-action="Index" asp-controller="ShoppingCart">
					<span class="icon_bag_alt"></span>
					<div class="tip">*</div>
				</a>

			</li>
		</ul>
		<div class="offcanvas__logo">
			<a href="./index.html"><img src="~/img/logo.png" alt=""></a>
		</div>
		<div id="mobile-menu-wrap"></div>
		<div class="offcanvas__auth">
			<a href="#">Login</a>
			<a href="#">Register</a>
		</div>
	</div>
	<!-- Offcanvas Menu End -->
	<!-- Header Section Begin -->
	<header class="header">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xl-3 col-lg-2">
					<div class="header__logo">
						<a href="./index.html"><img src="~/img/logo.png" alt=""></a>
					</div>
				</div>
				<div class="col-xl-6 col-lg-7">
					<nav class="header__menu">
						<ul id="myid">
							<li id="1"  ><a asp-action="Index" asp-controller="Home">Home</a></li>
							<li id="2"  ><a asp-action="Index" asp-controller="Shop">Shop</a></li>
							<li id="3"  ><a asp-action="Index" asp-controller="ShoppingCart">Shop Cart</a></li>
							<li id="4"  ><a href="./contact.html">Contact</a></li>
						</ul>
					</nav>
				</div>
				<div class="col-lg-3">
					<div class="header__right">
						<div class="header__right__auth">
							<a href="#">Login</a>
							<a href="#">Register</a>
						</div>
						<ul class="header__right__widget">
							<li>

				<a asp-action="Index" asp-controller="FavouriteProducts">

									<span class="icon_heart_alt"></span>
								</a>

							</li>
							<li>

				<a asp-action="Index" asp-controller="ShoppingCart">

									<span class="icon_bag_alt"></span>
								</a>

							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="canvas__open">
				<i class="fa fa-bars"></i>
			</div>
		</div>
	</header>
	<!-- Header Section End -->

	<div>
		@RenderBody()
	</div>

	<!-- Footer Section Begin -->
	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-6 col-sm-7">
					<div class="footer__about">
						<div class="footer__logo">
							<a href="./index.html"><img src="~/img/logo.png" alt=""></a>
						</div>
						<p>

							Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
							cilisis.

						</p>
						<div class="footer__payment">
							<a href="#"><img src="~/img/payment/payment-1.png" alt=""></a>
							<a href="#"><img src="~/img/payment/payment-2.png" alt=""></a>
							<a href="#"><img src="~/img/payment/payment-3.png" alt=""></a>
							<a href="#"><img src="~/img/payment/payment-4.png" alt=""></a>
							<a href="#"><img src="~/img/payment/payment-5.png" alt=""></a>
						</div>
					</div>
				</div>
				<div class="col-lg-2 col-md-3 col-sm-5">
					<div class="footer__widget">
						<h6>Quick links</h6>
						<ul>
							<li><a href="#">About</a></li>
							<li><a href="#">Blogs</a></li>
							<li><a href="#">Contact</a></li>
							<li><a href="#">FAQ</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-md-3 col-sm-4">
					<div class="footer__widget">
						<h6>Account</h6>
						<ul>
							<li><a href="#">My Account</a></li>
							<li><a href="#">Orders Tracking</a></li>
							<li><a href="#">Checkout</a></li>
							<li><a href="#">Wishlist</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4 col-md-8 col-sm-8">
					<div class="footer__newslatter">
						<h6>NEWSLETTER</h6>
						<form action="#">
							<input type="text" placeholder="Email">
							<button type="submit" class="site-btn">Subscribe</button>
						</form>
						<div class="footer__social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-youtube-play"></i></a>
							<a href="#"><i class="fa fa-instagram"></i></a>
							<a href="#"><i class="fa fa-pinterest"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					<div class="footer__copyright__text">
						<p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
					</div>
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				</div>
			</div>
		</div>
	</footer>
	<!-- Footer Section End -->
	<!-- Search Begin -->
	<div class="search-model">
		<div class="h-100 d-flex align-items-center justify-content-center">
			<div class="search-close-switch">+</div>
			<form class="search-model-form">
				<input type="text" id="search-input" placeholder="Search here.....">
			</form>
		</div>
	</div>
	<!-- Search End -->
	<!-- Js Plugins -->
	<script src="~/js/jquery-3.3.1.min.js"></script>
	<script src="~/js/bootstrap.min.js"></script>
	<script src="~/js/jquery.magnific-popup.min.js"></script>
	<script src="~/js/jquery-ui.min.js"></script>
	<script src="~/js/mixitup.min.js"></script>
	<script src="~/js/jquery.countdown.min.js"></script>
	<script src="~/js/jquery.slicknav.js"></script>
	<script src="~/js/owl.carousel.min.js"></script>
	<script src="~/js/jquery.nicescroll.min.js"></script>
	<script src="~/js/main.js"></script>
	<script type="text/javascript" src="~/js/multiselect-dropdown.js"></script>

	@await RenderSectionAsync("Scripts", required: false)
	
</body>
</html>